spring:
   application:
      name: productMicroservice
server:
   port: 8080
   ssl:
      enabled: false
      key-password: password
      key-store: classpath:keystore.jks
      key-store-password: password